Reflection_Wiz70_QA_7b:
  completions_kwargs:
    do_sample: true
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: bfloat16
    model_name: ./Reflection_Wiz70_QA_7b
    temperature: 0.7
    top_p: 1.0
  fn_completions: huggingface_local_completions
  link: ''
  pretty_name: Reflection_Wiz70_QA_7b
  prompt_template: vicuna-7b/prompt.txt
